### ISSUE TITLE
歌曲时长能否提供获取方法呢

### ISSUE THREAD

**Issue by lsaejn** [yiyungent/Meting4Net#8]
应该是常见需求呀

**Comment by yiyungent** [comment]
毕竟是调用本身音乐服务的api，如果别人没有提供音乐歌曲时长的话，那肯定没办法了，不可能调用的时候去下载保存然后计算时长吧

PS：使用返回json字符串的方法，就是原生音乐服务api的结果，没有音乐时长的话，那肯定没办法了

**Comment by lsaejn** [comment]
哈，我看到163的接口返回了时间，所以想当然地以为所有接口都支持这个
